GET http://localhost:8080/api/v1/receipts/:countDiscountedReceipt
Content-Type: application/json
Cookie: key=first-value

{"products":
[
  {
    "name" : "milk",
    "type" : "MEAT",
    "price" : "123"
  },
  {
    "name" : "milk",
    "type" : "MEAT",
    "price" : "123"
  }
]
}